-- This file is a reference map of storage.buckets, not a script that creates
-- them. None of the four buckets below were ever created by a tracked
-- migration -- they predate migration history the same way public.users/
-- mentors do; see .claude/rules/supabase-changes.md.
--
-- storage.buckets has separate `id` and `name` columns, and RLS/the Storage
-- API key off `id`, not `name`. `supabase storage ls --experimental` prints
-- `name`, which caused a false-alarm "unprotected bucket" investigation on
-- 2026-08-21 -- id and name differ for two of these four buckets. Confirmed
-- live via `SELECT id, name FROM storage.buckets`:
--
--   id               | name
--   -----------------+------------------------
--   profiles         | profile-images
--   team_members     | team_members
--   marketplace      | marketplace
--   community-posts  | Community Post Images
--
-- Policies below are written against `id`, which is what actually matters.
-- Two dashboard-created "Authenticated can list ..." SELECT policies got this
-- backwards (profile-images, Community Post Images) -- see their sections
-- below -- and 20260821100000_fix_storage_list_policy_bucket_ids.sql
-- corrects both.

-- ---------------------------------------------------------------------------
-- profile-images -- public read, owner-scoped write
-- ---------------------------------------------------------------------------
-- Policy names/definitions below are as tracked in migrations; the bucket
-- itself and its base policies were not.

-- CREATE POLICY "Users can upload their own profile images"
-- ON storage.objects FOR INSERT TO authenticated
-- WITH CHECK (bucket_id = 'profile-images' AND (auth.uid())::text = SUBSTRING(name FROM 'profile-images/([^-]+)-'));
--
-- CREATE POLICY "Profile images are publicly accessible"
-- ON storage.objects FOR SELECT TO public
-- USING (bucket_id = 'profile-images');
--
-- CREATE POLICY "Authenticated can list profile-images"
-- ON storage.objects FOR SELECT TO authenticated
-- USING (bucket_id = 'profiles');
-- Originally created against bucket_id = 'profile-images' (the display name)
-- by 20260418025448_a4b8a106-6764-4bb8-a590-f6cb7d3efc85.sql -- a no-op ever
-- since, fixed by 20260821100000_fix_storage_list_policy_bucket_ids.sql.

-- ---------------------------------------------------------------------------
-- team_members -- admin-only, gated by is_admin_user()
-- ---------------------------------------------------------------------------
-- (supabase/migrations/20260418025448_..., 20260804132345_...)

-- ---------------------------------------------------------------------------
-- marketplace -- owner-must-match on write
-- ---------------------------------------------------------------------------
-- (supabase/migrations/20260804132345_b843f814-46d5-4c25-bc80-32e5f6ebba59.sql)

-- ---------------------------------------------------------------------------
-- community-posts (display name "Community Post Images") -- owner-must-match
-- on write, public read
-- ---------------------------------------------------------------------------
-- The owner-scoped INSERT/UPDATE/DELETE policies
-- (20260804132345_b843f814-46d5-4c25-bc80-32e5f6ebba59.sql) always targeted
-- the correct id, bucket_id = 'community-posts'; writes were never
-- unprotected. The tracked "Authenticated can list community post images"
-- SELECT policy targeted the display name instead and was a no-op --
-- 20260821100000_fix_storage_list_policy_bucket_ids.sql corrects it.
