import { supabase } from "@/integrations/supabase/client";

export const VAPID_PUBLIC_KEY =
  import.meta.env.VITE_VAPID_PUBLIC_KEY ||
  "BKOAXjuHWTibnWSS7ncFnSVue84A_AYycGVEvqWT4gnIRwfJZxt7HxKjIjm7WlteDJf5sqkqeFTTHxAAtxAHsc4";

/**
 * Converts a base64 string to a Uint8Array for PushManager subscription.
 */
export function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, "+")
    .replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Checks if the current browser and OS support Web Push notifications.
 */
export function isPushNotificationSupported(): boolean {
  return (
    typeof window !== "undefined" &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window
  );
}

/**
 * Gets current notification permission state.
 */
export function getNotificationPermission(): NotificationPermission | "unsupported" {
  if (!isPushNotificationSupported()) return "unsupported";
  return Notification.permission;
}

/**
 * Registers the root Service Worker (/sw.js)
 */
export async function registerServiceWorker(): Promise<ServiceWorkerRegistration | null> {
  if (!isPushNotificationSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.register("/sw.js", {
      scope: "/",
    });
    return registration;
  } catch (error) {
    console.warn("[pushService] Service Worker registration failed:", error);
    return null;
  }
}

/**
 * Subscribes the current device to Web Push and saves the endpoint to Supabase.
 */
export async function subscribeUserToPush(userId: string): Promise<{ success: boolean; error?: string }> {
  if (!isPushNotificationSupported()) {
    return { success: false, error: "Push notifications are not supported in this browser." };
  }

  try {
    const permission = await Notification.requestPermission();
    if (permission !== "granted") {
      return { success: false, error: "Notification permission was not granted." };
    }

    const registration = await registerServiceWorker();
    if (!registration) {
      return { success: false, error: "Could not register service worker." };
    }

    await navigator.serviceWorker.ready;

    let subscription = await registration.pushManager.getSubscription();

    if (!subscription) {
      const applicationServerKey = urlBase64ToUint8Array(VAPID_PUBLIC_KEY);
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey,
      });
    }

    const subJson = subscription.toJSON();
    const endpoint = subJson.endpoint;
    const p256dh = subJson.keys?.p256dh;
    const auth = subJson.keys?.auth;

    if (!endpoint || !p256dh || !auth) {
      return { success: false, error: "Incomplete push subscription generated by browser." };
    }

    // Save or update subscription in Supabase
    const { error: dbError } = await (supabase as any)
      .from("push_subscriptions")
      .upsert(
        {
          user_id: userId,
          endpoint,
          p256dh,
          auth,
          user_agent: navigator.userAgent || null,
          updated_at: new Date().toISOString(),
        },
        { onConflict: "user_id,endpoint" }
      );

    if (dbError) {
      console.error("[pushService] Error saving subscription to DB:", dbError);
      return { success: false, error: dbError.message };
    }

    // Enable push preference on user profile
    await (supabase as any)
      .from("users")
      .update({ push_notifications_enabled: true })
      .eq("id", userId);

    return { success: true };
  } catch (err: any) {
    console.error("[pushService] Exception during subscribe:", err);
    return { success: false, error: err?.message || "Failed to enable notifications." };
  }
}

/**
 * Unsubscribes the current device and removes it from Supabase.
 */
export async function unsubscribeUserFromPush(userId: string): Promise<{ success: boolean; error?: string }> {
  if (!isPushNotificationSupported()) {
    return { success: true };
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const endpoint = subscription.endpoint;
      await subscription.unsubscribe();

      await (supabase as any)
        .from("push_subscriptions")
        .delete()
        .eq("user_id", userId)
        .eq("endpoint", endpoint);
    }

    return { success: true };
  } catch (err: any) {
    console.error("[pushService] Error unsubscribing:", err);
    return { success: false, error: err?.message };
  }
}

/**
 * Triggers a Web Push notification dispatch through the Supabase Edge Function.
 */
export async function dispatchPushNotification(opts: {
  userIds: string[] | string;
  title: string;
  body: string;
  url?: string;
  tag?: string;
  icon?: string;
  data?: Record<string, unknown>;
}): Promise<boolean> {
  try {
    const rawIds = Array.isArray(opts.userIds) ? opts.userIds : [opts.userIds];
    const userIds = rawIds.filter(Boolean);

    if (userIds.length === 0) return false;

    const { error } = await supabase.functions.invoke("send-push", {
      body: {
        userIds,
        title: opts.title,
        body: opts.body,
        url: opts.url || "/",
        tag: opts.tag || "campus-notification",
        icon: opts.icon || "/pwa-192x192.png",
        badge: "/badge-96x96.png",
        data: opts.data,
      },
    });

    if (error) {
      console.warn("[pushService] Push function dispatch warning:", error);
      return false;
    }

    return true;
  } catch (err) {
    console.warn("[pushService] Failed to dispatch push notification:", err);
    return false;
  }
}
