import { supabase } from "@/integrations/supabase/client";

/**
 * The server's VAPID public key. Public by design, so it is a constant here
 * rather than an environment variable: an env var that could still hold the
 * old key in some deployment would silently create subscriptions send-push can
 * no longer sign for. Must match the VAPID_PUBLIC_KEY secret on send-push.
 *
 * Rotated 2026-09-14 because the previous pair's private key had been committed
 * to this public repo. Browsers subscribed with the old key are moved to this
 * one by ensureSubscriptionUsesCurrentKey().
 */
export const VAPID_PUBLIC_KEY =
  "BMK1v09pBmGu9R5nbJSOPAiwoE8RNlX29gxSzYE7PyL0W18Ibk1pPRow3hfb0OIVrDkHH7vbY8TUDC-IkiSwbSo";

/**
 * Converts a base64 string to a Uint8Array for PushManager subscription.
 */
export function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding)
    .replace(/-/g, "+")
    .replace(/_/g, "/");

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

function sameBytes(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

/** True when the subscription was created with a different server key than VAPID_PUBLIC_KEY. Unknown counts as current. */
function usesStaleKey(subscription: PushSubscription): boolean {
  const key = subscription.options?.applicationServerKey;
  if (!key) return false;
  return !sameBytes(new Uint8Array(key), urlBase64ToUint8Array(VAPID_PUBLIC_KEY));
}

async function saveSubscription(userId: string, subscription: PushSubscription): Promise<{ error?: string }> {
  const subJson = subscription.toJSON();
  const endpoint = subJson.endpoint;
  const p256dh = subJson.keys?.p256dh;
  const auth = subJson.keys?.auth;
  if (!endpoint || !p256dh || !auth) {
    return { error: "Incomplete push subscription generated by browser." };
  }
  const { error } = await supabase
    .from("push_subscriptions")
    .upsert(
      {
        user_id: userId,
        endpoint,
        p256dh,
        auth,
        user_agent: navigator.userAgent || null,
        updated_at: new Date().toISOString(),
      },
      { onConflict: "user_id,endpoint" }
    );
  if (error) {
    console.error("[pushService] Error saving subscription to DB:", error);
    return { error: error.message };
  }
  return {};
}

let keyMigration: Promise<void> | null = null;

/**
 * Moves this browser's push subscription to the current VAPID key, once per
 * page load, without asking the user again: notification permission belongs
 * to the site, not the key, so an already-granted browser can re-subscribe
 * silently. Several components mount usePushNotifications at once, hence the
 * shared promise.
 */
export function ensureSubscriptionUsesCurrentKey(userId: string): Promise<void> {
  if (keyMigration) return keyMigration;
  keyMigration = (async () => {
    try {
      if (!isPushNotificationSupported() || Notification.permission !== "granted") return;
      const registration = await navigator.serviceWorker.getRegistration("/");
      const subscription = await registration?.pushManager.getSubscription();
      if (!registration || !subscription || !usesStaleKey(subscription)) return;

      const oldEndpoint = subscription.endpoint;
      await subscription.unsubscribe();
      await supabase.from("push_subscriptions").delete().eq("user_id", userId).eq("endpoint", oldEndpoint);

      const fresh = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
      });
      await saveSubscription(userId, fresh);
    } catch (err) {
      console.warn("[pushService] Could not move subscription to the current key:", err);
    }
  })();
  return keyMigration;
}

/**
 * Checks if the current browser and OS support Web Push notifications.
 */
export function isPushNotificationSupported(): boolean {
  return (
    typeof window !== "undefined" &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window
  );
}

/**
 * Gets current notification permission state.
 */
export function getNotificationPermission(): NotificationPermission | "unsupported" {
  if (!isPushNotificationSupported()) return "unsupported";
  return Notification.permission;
}

/**
 * Registers the root Service Worker (/sw.js)
 */
export async function registerServiceWorker(): Promise<ServiceWorkerRegistration | null> {
  if (!isPushNotificationSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.register("/sw.js", {
      scope: "/",
    });
    return registration;
  } catch (error) {
    console.warn("[pushService] Service Worker registration failed:", error);
    return null;
  }
}

/**
 * Subscribes the current device to Web Push and saves the endpoint to Supabase.
 */
export async function subscribeUserToPush(userId: string): Promise<{ success: boolean; error?: string }> {
  if (!isPushNotificationSupported()) {
    return { success: false, error: "Push notifications are not supported in this browser." };
  }

  try {
    const permission = await Notification.requestPermission();
    if (permission !== "granted") {
      return { success: false, error: "Notification permission was not granted." };
    }

    const registration = await registerServiceWorker();
    if (!registration) {
      return { success: false, error: "Could not register service worker." };
    }

    await navigator.serviceWorker.ready;

    let subscription = await registration.pushManager.getSubscription();

    // A subscription made with a previous server key cannot receive pushes
    // signed with the current one; replace it rather than re-saving it.
    if (subscription && usesStaleKey(subscription)) {
      await subscription.unsubscribe();
      subscription = null;
    }

    if (!subscription) {
      const applicationServerKey = urlBase64ToUint8Array(VAPID_PUBLIC_KEY);
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey,
      });
    }

    const saved = await saveSubscription(userId, subscription);
    if (saved.error) {
      return { success: false, error: saved.error };
    }

    // Enable push preference on user profile
    await supabase
      .from("users")
      .update({ push_notifications_enabled: true })
      .eq("id", userId);

    return { success: true };
  } catch (err: any) {
    console.error("[pushService] Exception during subscribe:", err);
    return { success: false, error: err?.message || "Failed to enable notifications." };
  }
}

/**
 * Unsubscribes the current device and removes it from Supabase.
 */
export async function unsubscribeUserFromPush(userId: string): Promise<{ success: boolean; error?: string }> {
  if (!isPushNotificationSupported()) {
    return { success: true };
  }

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const endpoint = subscription.endpoint;
      await subscription.unsubscribe();

      await supabase
        .from("push_subscriptions")
        .delete()
        .eq("user_id", userId)
        .eq("endpoint", endpoint);
    }

    return { success: true };
  } catch (err: any) {
    console.error("[pushService] Error unsubscribing:", err);
    return { success: false, error: err?.message };
  }
}

/**
 * Triggers a Web Push notification dispatch through the Supabase Edge Function.
 */
export async function dispatchPushNotification(opts: {
  userIds: string[] | string;
  title: string;
  body: string;
  url?: string;
  tag?: string;
  icon?: string;
  data?: Record<string, unknown>;
}): Promise<boolean> {
  try {
    const rawIds = Array.isArray(opts.userIds) ? opts.userIds : [opts.userIds];
    const userIds = rawIds.filter(Boolean);

    if (userIds.length === 0) return false;

    const { error } = await supabase.functions.invoke("send-push", {
      body: {
        userIds,
        title: opts.title,
        body: opts.body,
        url: opts.url || "/",
        tag: opts.tag || "campus-notification",
        icon: opts.icon || "/pwa-192x192.png",
        badge: "/badge-96x96.png",
        data: opts.data,
      },
    });

    if (error) {
      console.warn("[pushService] Push function dispatch warning:", error);
      return false;
    }

    return true;
  } catch (err) {
    console.warn("[pushService] Failed to dispatch push notification:", err);
    return false;
  }
}
