// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rubfljzafzwlpzszqaig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1YmZsanphZnp3bHB6c3pxYWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3OTgwNjMsImV4cCI6MjA1NjM3NDA2M30.iNxBt-wDxvuSPX7saX8Ow6-uv_My7IrwBWrtF9xvTeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);