
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruapdkrgcbqrhvsayvpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1YXBka3JnY2Jxcmh2c2F5dnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODU5NzMsImV4cCI6MjA1NjQ2MTk3M30.V5jQfO-__C1gSbX33c2M-iBouFVWbO1bSPnRlc9iw1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get typed data from Supabase tables
export async function getMentors() {
  const { data, error } = await supabase
    .from('mentors')
    .select('*');
  
  return { data, error };
}

export async function addMentor(mentor: {
  name: string;
  department: string;
  skills: string[];
  rating: number;
  profile_image: string;
  linkedin_url?: string;
  bio?: string;
  review_count?: number;
}) {
  return supabase
    .from('mentors')
    .insert([mentor]);
}

export async function searchMentors(query: string) {
  if (!query.trim()) {
    return getMentors();
  }
  
  const lowerQuery = query.toLowerCase();
  
  // Search in name, department, skills, and bio
  const { data, error } = await supabase
    .from('mentors')
    .select('*')
    .or(`
      name.ilike.%${lowerQuery}%,
      department.ilike.%${lowerQuery}%,
      bio.ilike.%${lowerQuery}%
    `)
    .order('rating', { ascending: false });
    
  // For skills array, we need to filter in JS since it's complex in SQL
  const filteredData = data?.filter(mentor => 
    mentor.skills.some(skill => 
      skill.toLowerCase().includes(lowerQuery)
    )
  ) || [];
  
  // Merge SQL results with JS filtered results for skills
  const mergedResults = [...(data || []), ...filteredData];
  
  // Remove duplicates based on id
  const uniqueResults = Array.from(
    new Map(mergedResults.map(item => [item.id, item])).values()
  );
  
  return { data: uniqueResults, error };
}
