
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { Message, Conversation } from '@/types/chat';

const SUPABASE_URL = "https://ruapdkrgcbqrhvsayvpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1YXBka3JnY2Jxcmh2c2F5dnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODU5NzMsImV4cCI6MjA1NjQ2MTk3M30.V5jQfO-__C1gSbX33c2M-iBouFVWbO1bSPnRlc9iw1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get typed data from Supabase tables
export async function getMentors() {
  const { data, error } = await supabase
    .from('mentors')
    .select('*');
  
  return { data, error };
}

export async function addMentor(mentor: {
  name: string;
  department: string;
  skills: string[];
  rating: number;
  profile_image: string;
  linkedin_url?: string;
  bio?: string;
  review_count?: number;
}) {
  return supabase
    .from('mentors')
    .insert([mentor]);
}

export async function searchMentors(query: string) {
  if (!query.trim()) {
    return getMentors();
  }
  
  const lowerQuery = query.toLowerCase();
  
  // Search in name, department, skills, and bio
  const { data, error } = await supabase
    .from('mentors')
    .select('*')
    .or(`
      name.ilike.%${lowerQuery}%,
      department.ilike.%${lowerQuery}%,
      bio.ilike.%${lowerQuery}%
    `)
    .order('rating', { ascending: false });
    
  // For skills array, we need to filter in JS since it's complex in SQL
  const filteredData = data?.filter(mentor => 
    mentor.skills.some(skill => 
      skill.toLowerCase().includes(lowerQuery)
    )
  ) || [];
  
  // Merge SQL results with JS filtered results for skills
  const mergedResults = [...(data || []), ...filteredData];
  
  // Remove duplicates based on id
  const uniqueResults = Array.from(
    new Map(mergedResults.map(item => [item.id, item])).values()
  );
  
  return { data: uniqueResults, error };
}

// Get a single mentor by ID
export async function getMentorById(id: string) {
  const { data, error } = await supabase
    .from('mentors')
    .select('*')
    .eq('id', id)
    .single();
  
  return { data, error };
}

// Chat functionality - Using RPC functions for conversations and messages

// Get or create a conversation between two users
export async function getOrCreateConversation(user1Id: string, user2Id: string) {
  try {
    // First check if a conversation already exists
    const { data, error } = await supabase
      .rpc('get_conversation', { 
        user1: user1Id, 
        user2: user2Id 
      });

    if (error) {
      console.error('Error searching for conversation:', error);
      return { data: null, error };
    }

    if (data && data.length > 0) {
      return { data: data[0] as Conversation, error: null };
    }

    // If no conversation exists, create a new one
    const { data: newConversation, error: createError } = await supabase
      .rpc('create_conversation', {
        user1_id: user1Id,
        user2_id: user2Id
      });

    return { 
      data: newConversation as Conversation, 
      error: createError 
    };
  } catch (err) {
    console.error('Exception in getOrCreateConversation:', err);
    return { data: null, error: err as Error };
  }
}

// Get messages for a conversation
export async function getConversationMessages(conversationId: string) {
  try {
    const { data, error } = await supabase
      .rpc('get_conversation_messages', { 
        conversation_id: conversationId 
      });

    return { 
      data: data as Message[], 
      error 
    };
  } catch (err) {
    console.error('Exception in getConversationMessages:', err);
    return { data: null, error: err as Error };
  }
}

// Send a message in a conversation
export async function sendMessage(conversationId: string, senderId: string, receiverId: string, content: string) {
  try {
    // Insert the message
    const { data, error: messageError } = await supabase
      .rpc('send_message', {
        conversation_id: conversationId,
        sender_id: senderId,
        receiver_id: receiverId,
        content: content
      });

    if (messageError) {
      console.error('Error sending message:', messageError);
      return { data: null, error: messageError };
    }

    // Update the conversation with the last message
    const { error: updateError } = await supabase
      .rpc('update_conversation', {
        conversation_id: conversationId,
        last_message: content
      });

    if (updateError) {
      console.error('Error updating conversation:', updateError);
    }

    return { 
      data: data as Message, 
      error: updateError 
    };
  } catch (err) {
    console.error('Exception in sendMessage:', err);
    return { data: null, error: err as Error };
  }
}

// Get all conversations for a user
export async function getUserConversations(userId: string) {
  try {
    const { data, error } = await supabase
      .rpc('get_user_conversations', { 
        user_id: userId 
      });

    return { 
      data: data as Conversation[], 
      error 
    };
  } catch (err) {
    console.error('Exception in getUserConversations:', err);
    return { data: null, error: err as Error };
  }
}

// Mark messages as read
export async function markMessagesAsRead(conversationId: string, userId: string) {
  try {
    const { error } = await supabase
      .rpc('mark_messages_as_read', {
        conversation_id: conversationId,
        user_id: userId
      });

    return { error };
  } catch (err) {
    console.error('Exception in markMessagesAsRead:', err);
    return { error: err as Error };
  }
}
